export const getProductsAction = async () => {
  try {
    console.log(getProductsAction);
  } catch (error) {
    console.log('Error: ', error);
    throw new Error('Unexpected error');
  }
};
